[minecraft]
# Path to your install of java. In this case, defaults to the installed java version
java_path = "java"
# The file name for the server jar, this is used to find the file on disk so wildcards can be used
server_jar = "minecraft_*.jar"
# JVM args to use. Change as you see fit
jvm_args = ['-Xms1G', '-Xmx2G']

[minecraft.restarts]
# Whether or not to restart the server
auto_restart = false
# Time in hours between server restarts
restart_interval = 6
# Intervals (in seconds) to alert of a pending server restart
alert_intervals = [3600, 1800, 300, 30]

[minecraft.console]
# Section of regexes for handling server output for various things. 
# You may need to adjust these if you install server software like minecraftforge
player_connected = '(?P<username>[\w]+)\[\/(?P<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d+)] logged in with entity id [0-9]+ at \(.*\)'
player_disconnected = '(?P<username>[A-Za-z0-9_]{1,16}) lost connection: (?P<reason>.+)'
# If you have a plugin that changes player chat, you will need to change this to get chat history working.
# It's also used to stop people from triggering the above two regexes using chat messages so this is important!
player_chat = '\]: <(?P<username>[A-Za-z0-9_]{1,16})> (?P<message>.*?)$'
